name: Scrape Talk Locations

on:
  push:
    paths:
      - 'talks/**'
      - '_talks/**'
      - 'talkmap.ipynb'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write           # This workflow pushes to the repository

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'   # Specify the Python version you need



    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install jupyter nbconvert nbclient ipykernel
        pip install pandas requests beautifulsoup4 geopy getorg
        python -m ipykernel install --user --name python3 --display-name "Python 3"



    - name: Run Jupyter Notebook
      run: |
        jupyter nbconvert --to notebook --execute talkmap.ipynb --output talkmap_out.ipynb



    - name: Run Jupyter Notebook
      run: |
        jupyter nbconvert --to notebook --execute talkmap.ipynb \
          --ExecutePreprocessor.kernel_name=python3 \
          --output talkmap_out.ipynb

    - name: Commit changes
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add .
        git commit -m "Automated update of talk locations" || echo "No changes to commit"
        git push
